const fs = require('fs');

const raw = fs.readFileSync('scenarios.json', 'utf8');
let data = JSON.parse(raw);

function generateFollowUps(scenario) {
    const title = scenario.title || scenario.topic || '';
    const tags = (scenario.chips || scenario.tags || []).map(t => t.toLowerCase());
    const textContext = (scenario.definition || scenario.problem || '').toLowerCase();
    
    let questions = [];

    // Generic Interview Pressure Questions (apply to any scenario to see how they handle stress)
    const generic = [
        `How would you explain the business impact of ${title} to a non-technical stakeholder?`,
        `Can you describe a time when your assumptions about ${title} were wrong in production?`,
        `If you had an unlimited budget, how would you redesign your approach to ${title}?`,
        `How do you measure the success or failure of your implementation for ${title}?`,
        `What is the most common anti-pattern you see junior engineers make with ${title}?`
    ];

    // Domain specific templates
    if (title.toLowerCase().includes('kubernetes') || title.toLowerCase().includes('aks') || tags.includes('kubernetes')) {
        questions.push(`How does ${title} behave during a sudden cluster autoscaler scale-down event?`);
        questions.push(`What specific Prometheus metrics would you monitor to ensure ${title} is healthy?`);
        questions.push(`How would you secure the RBAC permissions related to ${title}?`);
        questions.push(`What happens to ${title} if the Kubernetes Control Plane becomes temporarily unreachable?`);
        questions.push(`How does an underlying network plugin (like Azure CNI or Calico) impact the performance of ${title}?`);
        questions.push(`If a pod related to ${title} gets stuck in 'Terminating', how do you safely force it out?`);
    }

    if (title.toLowerCase().includes('terraform') || tags.includes('terraform') || tags.includes('iac')) {
        questions.push(`How do you manage the blast radius when executing ${title} across multiple environments?`);
        questions.push(`What is your strategy for handling state file locks during a pipeline failure involving ${title}?`);
        questions.push(`How would you refactor ${title} into a reusable, versioned module?`);
        questions.push(`Can you explain how 'terraform import' would be utilized if ${title} was created manually?`);
        questions.push(`What security checks (like Checkov or tfsec) would you enforce on ${title} in the CI pipeline?`);
    }

    if (title.toLowerCase().includes('azure') || tags.includes('azure') || tags.includes('cloud')) {
        questions.push(`Which Azure networking features (like Private Link or Service Endpoints) would secure ${title}?`);
        questions.push(`How do you implement disaster recovery across multiple Azure regions for ${title}?`);
        questions.push(`What role does Azure Managed Identities play in the architecture of ${title}?`);
        questions.push(`How would you optimize the FinOps/billing costs associated with ${title}?`);
        questions.push(`If Azure active directory experiences an outage, how does it affect ${title}?`);
    }

    if (title.toLowerCase().includes('pipeline') || title.toLowerCase().includes('jenkins') || title.toLowerCase().includes('github') || tags.includes('ci/cd')) {
        questions.push(`How do you achieve zero-downtime deployments when implementing ${title}?`);
        questions.push(`What caching strategies would you use to reduce the execution time of ${title}?`);
        questions.push(`How do you handle database schema migrations within the context of ${title}?`);
        questions.push(`What manual approval gates or checks are necessary before ${title} reaches production?`);
        questions.push(`How do you ensure secrets are not leaked in the logs generated by ${title}?`);
    }

    if (title.toLowerCase().includes('outage') || title.toLowerCase().includes('failing') || tags.includes('troubleshooting')) {
        questions.push(`During the ${title} incident, how do you prioritize mitigation versus root cause analysis?`);
        questions.push(`What exact Grafana queries or dashboards would have caught ${title} before the customer did?`);
        questions.push(`How do you structure the blameless post-mortem for ${title}?`);
        questions.push(`If mitigation for ${title} requires an emergency hotfix, what steps do you skip in the CI/CD pipeline?`);
        questions.push(`How do you manage communication with stakeholders during a Sev-1 related to ${title}?`);
    }

    // Mix and select exactly 6 questions
    let finalQuestions = [];
    
    // Get 4 from domain specific (if available)
    let domainSpecific = questions.sort(() => 0.5 - Math.random());
    finalQuestions.push(...domainSpecific.slice(0, 4));

    // Fill the rest with generics to hit 6
    let genericShuffle = generic.sort(() => 0.5 - Math.random());
    while(finalQuestions.length < 6 && genericShuffle.length > 0) {
        let q = genericShuffle.pop();
        if(q && !finalQuestions.includes(q)) finalQuestions.push(q);
    }

    // Clean up title text in questions (sometimes title is too long, but it works fine for interview simulation)
    return finalQuestions.filter(q => q).map(q => q.replace(/  /g, ' '));
}

let updated = 0;
data.forEach((s) => {
    // Overwrite existing follow-ups if they have less than 5 to meet the prompt requirement
    if (!s.follow_up_questions || s.follow_up_questions.length < 5) {
        s.follow_up_questions = generateFollowUps(s);
        updated++;
    }
});

fs.writeFileSync('scenarios.json', JSON.stringify(data, null, 2));
console.log('Injected 6 specific Follow-Up questions for ' + updated + ' scenarios.');
